# Generated by Django 5.2 on 2025-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estilo', models.CharField(choices=[('Realismo', 'realismo'), ('Tradicional', 'tradicional'), ('Neotradicional', 'neotradicional'), ('Acuarela', 'acuarela'), ('Geométrico', 'geométrico'), ('BlackWork', 'blackwork'), ('Trival', 'trival'), ('Sigilo', 'sigilo')], max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tattoos/')),
                ('artista', models.CharField(choices=[('Xavier Verdecie Ramos', 'xavier verdecie ramos'), ('Osmel Medero Rosales', 'osmel medero rosales')], max_length=30)),
            ],
            options={
                'verbose_name': 'Tattoo',
                'verbose_name_plural': 'Tattoos',
            },
        ),
    ]
