# Generated by Django 4.2.20 on 2025-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
