# Generated by Django 4.2.20 on 2025-05-03 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tattoo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Piercing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ubi', models.CharField(choices=[('Lóbulo', 'lobulo'), ('Helix', 'helix'), ('Tragus', 'tragus'), ('Antitragus', 'antitragus'), ('Daith', 'daith'), ('Rook', 'rook'), ('Conch', 'conch'), ('Snug', 'snug'), ('Industrial', 'industrial'), ('Septum', 'septum'), ('Fosa nasal', 'fosa nasal'), ('Labret', 'labret'), ('Medusa', 'medusa'), ('Ceja', 'ceja'), ('Ombligo', 'ombligo'), ('Pezón', 'pezon'), ('Surface', 'surface'), ('Microdermal', 'microdermal')], max_length=255)),
                ('foto', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Piercing',
                'verbose_name_plural': 'Piercings',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Aguja Americana 14', 'aguja americana 14'), ('Labret', 'labret'), ('Industrial', 'industrial'), ('Aguja RL5', 'aguja RL5'), ('Aguja RL7', 'aguja RL7'), ('Tinta Negra Oz', 'tinta negra Oz'), ('Paquete Toallitas Humedas', 'paquete toallitas humedas')], max_length=30)),
                ('cat', models.CharField(choices=[('Piercing', 'piercing'), ('Cuidado', 'cuidado'), ('Materiales', 'materiales')], max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True)),
                ('foto', models.CharField(blank=True, max_length=500, null=True)),
                ('disponible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Reporte_Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('Entregado', 'entregado'), ('Pedido', 'pedido')], default='Pedido', max_length=255)),
                ('fecha_pedido', models.DateField(default=datetime.date.today)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('costoTot', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True)),
                ('productos', models.ManyToManyField(through='app.ItemPedido', to='app.producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.reporte_abastecimiento'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
