# Generated by Django 4.2.20 on 2025-05-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_itempedido_piercing_producto_reporte_abastecimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte_abastecimiento',
            options={'verbose_name': 'Reporte_Abastecimiento', 'verbose_name_plural': 'Reportes_Abastecimiento'},
        ),
        migrations.RemoveField(
            model_name='reporte_abastecimiento',
            name='productos',
        ),
    ]
