# Generated by Django 4.2.20 on 2025-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reporte_abastecimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_v',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cat',
            field=models.CharField(choices=[('piercing', 'Piercing'), ('cuidado', 'Cuidado'), ('materiales', 'Materiales')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(choices=[('aguja_americana_14', 'Aguja Americana 14'), ('labret', 'Labret'), ('industrial', 'Industrial'), ('aguja_rl5', 'Aguja RL5'), ('aguja_rl7', 'Aguja RL7'), ('tinta_negra_oz', 'Tinta Negra Oz'), ('paquete_toallitas_humedas', 'Paquete Toallitas Humedas')], max_length=50),
        ),
    ]
