# Generated by Django 4.2.20 on 2025-05-05 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_fecha_v_alter_producto_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cliente', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1)),
                ('aporte', models.IntegerField(blank=True, null=True)),
                ('productos', models.ManyToManyField(to='app.producto')),
            ],
            options={
                'verbose_name': 'Reporte_Venta',
                'verbose_name_plural': 'Reportes_Venta',
            },
        ),
    ]
