# Generated by Django 4.2.20 on 2025-05-05 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reporte_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Uso_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2025, 5, 5))),
                ('cantidad', models.IntegerField(default=1)),
                ('materiales', models.ManyToManyField(to='app.producto')),
            ],
            options={
                'verbose_name': 'Reporte_Uso_Material',
                'verbose_name_plural': 'Reportes_Uso_Material',
            },
        ),
    ]
