# Generated by Django 4.2.20 on 2025-05-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0007_reporte_uso_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='piercing',
            name='precio',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='piercing',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reporte_Finanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
