# Generated by Django 4.2.20 on 2025-05-14 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_piercing_precio_piercing_public_tattoo_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piercing',
            name='precio',
        ),
        migrations.AlterField(
            model_name='reporte_uso_material',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 14)),
        ),
    ]
