# Generated by Django 4.2.20 on 2025-05-15 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_piercing_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_uso_material',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 15)),
        ),
    ]
